{'content': 'error', 'error_message': 'Error Type: Exception, Error File Location: main.py, Error Line: 45, Error Generator Class: EntityProcessor'}